# Generated by Django 3.2.13 on 2022-12-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
