# Generated by Django 3.2.13 on 2022-11-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_category',
            field=models.CharField(choices=[('서양화', '서양화'), ('동양화', '동양화'), ('판화', '판화'), ('일러스트', '일러스트'), ('조소', '조소'), ('설치미술', '설치미술'), ('사진', '사진')], max_length=10),
        ),
    ]
