# Generated by Django 3.2.13 on 2022-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='painted_year',
            field=models.DateTimeField(),
        ),
    ]
