# Generated by Django 3.2.13 on 2022-12-09 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_art_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_arts', to=settings.AUTH_USER_MODEL),
        ),
    ]
