# Generated by Django 3.2.13 on 2022-12-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_art_painted_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='painted_year',
            field=models.CharField(max_length=20),
        ),
    ]
