# Generated by Django 3.2.13 on 2022-12-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creater_name',
            field=models.CharField(blank=True, default='기모링', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, default='hello', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_creater',
            field=models.BooleanField(default=False),
        ),
    ]
