# Generated by Django 3.2.13 on 2022-12-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_detail',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
