# Generated by Django 3.2.13 on 2022-12-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221207_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='instargram',
            new_name='instagram',
        ),
    ]
