# Generated by Django 3.2.13 on 2022-12-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
