# Generated by Django 3.2.13 on 2022-12-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requests',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
