# Generated by Django 3.2.13 on 2022-12-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_art_order'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arts',
            field=models.ManyToManyField(related_name='ordered_art', to='articles.Art'),
        ),
    ]
