# Generated by Django 3.2.13 on 2022-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20221205_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('부재시 문 앞에 놓아주세요.', '부재시 문 앞에 놓아주세요.'), ('부재시 경비실에 맡겨주세요.', '부재시 경비실에 맡겨주세요.'), ('부재시 전화 또는 문자주세요.', '부재시 전화 또는 문자 주세요.'), ('택배함에 넣어주세요.', '택배함에 넣어주세요.'), ('파손위험이 있는 상품입니다. 배송 시 주의해주세요.', '파손위험이 있는 상품입니다. 배송 시 주의해주세요.'), ('배송 전에 연락주세요.', '배송 전에 연락주세요.')], default='부재시 문 앞에 놓아주세요.', max_length=50),
        ),
    ]
