# Generated by Django 3.2.13 on 2022-12-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requests',
            field=models.TextField(max_length=100),
        ),
    ]
